### ISSUE TITLE
Create app friendly layout

### ISSUE THREAD

**Issue by matthewcrist** [CityOfBoston/boston.gov#500]
Currently the layouts we use for apps comes with a lot of cruft and requires the basehref set to boston.gov. We need to create a layout that can be more easily consumed by these apps.

This is blocking cityofboston/311#60

## Tasks

 - [x] Create basic layout
 - [x] Add header to Crispus
 - [x] Add main navigation to Crispus
 - [x] Integrate header and main navigation into Drupal
 - [x] Create way to hide seal
 - [x] Remove all JS script tag dependencies from header and main navigation

## Acceptance criteria

 - External apps can pull header and footer from Boston.gov
 - App friendly template contains no JS script tag dependencies
 - App friendly template uses absolute URLs and doesn't rely on basehref

**Comment by joshuagee** [comment]
Met with DND and there's some desire to have Salesforce pull in headers and footers like this for their web interface. Still getting additional specs but I think what you're working on should cover it. @jimafisk

**Comment by matthewcrist** [comment]
This is available for testing at: https://edit-dev.boston.gov/api/v1/layouts/app

**Comment by jimafisk** [comment]
For reference, this is what we're using for jekyll: https://edit-dev.boston.gov/api/v1/layouts/generic
